name: quickzingo
description: "Boda Delivery"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  firebase_core: ^3.9.0
  http: ^1.5.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png

flutter_native_splash:
  color: "#FFD700"
  color_dark: "#FFD700"
  image: assets/splash/splash_icon.png
  image_dark: assets/splash/splash_icon.png
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: center
  android_12:
    image: assets/splash/splash_icon.png
    icon_background_color: "#FFD700"
    image_dark: assets/splash/splash_icon.png
    icon_background_color_dark: "#FFD700"
